// Lokální data pro demo režim (bez Supabase). Obsahově odpovídají supabase/seed.sql.
window.DEMO_DATA = {
  members: [
    { id: "member-s", slug: "s", display_name: "Silvie", initial: "S", is_admin: true,  hue: 32,  sort_order: 1, host_question: "Kolik máme oranžových koček?" },
    { id: "member-m", slug: "m", display_name: "Marek",  initial: "M", is_admin: false, hue: 190, sort_order: 2, host_question: null },
    { id: "member-z", slug: "z", display_name: "Zbyněk", initial: "Z", is_admin: false, hue: 330, sort_order: 3, host_question: null },
  ],

  // [název, min hráčů, max hráčů, soubor obrázku, vlastníci (slugy)]
  games: [
    ["Azul", 2, 4, "azul.png", ["s"]],
    ["Quartino", 2, 4, "quartino.png", ["s"]],
    ["Genius Square", 1, 2, "genius-square.png", ["s"]],
    ["Munchkin", 3, 6, "munchkin.png", ["s"]],
    ["Bájné kostky", 3, 6, "bajne-kostky.png", ["s"]],
    ["Krycí jména", 2, 8, "kryci-jmena.png", ["s"]],
    ["Krycí jména – Obrázky", 2, 8, "kryci-jmena-obrazky.png", ["s"]],
    ["Vydry", 3, 5, "vydry.png", ["s"]],
    ["Flip 7", 3, 18, "flip-7.png", ["s"]],
    ["Podělaná smůla", 3, 7, "podelana-smula.png", ["s"]],
    ["Trio", 3, 6, "trio.png", ["s"]],
    ["The Mind", 2, 4, "the-mind.png", ["s"]],
    ["Pirátské kostky", 2, 5, "piratske-kostky.png", ["s"]],
    ["Codex Naturalis", 2, 4, "codex-naturalis.png", ["s"]],
    ["Osmero", 2, 6, "osmero.png", ["s"]],
    ["U mě dobrý", 2, 5, "u-me-dobry.png", ["s"]],
    ["All in", 2, 5, "all-in.png", ["s"]],
    ["Ovce v masce", 2, 6, "ovce-v-masce.png", ["s"]],
    ["Naiši", 2, 2, "naishi.png", ["s"]],
    ["Word Bits", 2, 6, "word-bits.png", ["s"]],
    ["Jungo", 3, 5, "jungo.png", ["s"]],
    ["6 bere! Baron Vůl", 2, 10, "6-bere-baron-vul.png", ["s"]],
    ["Zlato nebo život", 2, 2, "zlato-nebo-zivot.png", ["s"]],
    ["Ztracená města", 2, 2, "ztracena-mesta.png", ["s"]],
    ["Monopoly", 2, 6, "monopoly.png", ["s"]],
    ["Othello na cesty", 2, 2, "othello-na-cesty.png", ["s"]],
    ["Bang!", 4, 7, "bang.png", ["s"]],
    ["Město duchů Bang!", 3, 8, "bang-mesto-duchu.png", ["s"]],
    ["Canasta The Simpsons", 1, 99, "canasta-simpsons.png", ["s"]],
    ["Canasta Gothic", 1, 99, "canasta-gothic.png", ["s"]],
    ["echoes KOKTEJL", 1, 6, "echoes-koktejl.png", ["s"]],
    ["70tá léta – Kvízy do kapsy", 1, 6, "70ta-leta-kvizy.png", ["s"]],
    ["1%", 2, 6, "jedno-procento.png", ["s"]],
    ["Atol", 1, 4, "atol.png", ["s"]],
    ["Bossin' Space", 1, 5, "bossin-space.png", ["s"]],
    ["Dej sem totem", 2, 2, "dej-sem-totem.png", ["s"]],
    ["Endless Winter: Paleoamericans", 1, 4, "endless-winter-paleoamericans.png", ["s"]],
    ["Endless Winter: Ancestors", 1, 4, "endless-winter-ancestors.png", ["s"]],
    ["Endless Winter: Cave Paintings", 1, 4, "endless-winter-cave-paintings.png", ["s"]],
    ["Endless Winter: Rivers and Rafts", 1, 4, "endless-winter-rivers-and-rafts.png", ["s"]],
    ["Endless Winter: Moduly", 1, 4, "endless-winter-moduly.png", ["s"]],
    ["Kvízový road trip", 1, 99, "kvizovy-road-trip.png", ["s"]],
    ["Orion", 2, 2, "orion.png", ["s"]],
    ["Pade", 3, 7, "pade.png", ["s"]],
    ["Podivuhodná stvoření", 1, 4, "podivuhodna-stvoreni.png", ["s"]],
    ["Projekt A.R.T.", 1, 6, "projekt-a-r-t.png", ["s"]],
    ["Rok pandy", 2, 5, "rok-pandy.png", ["s"]],
    ["Rybí trh Ukidzi", 2, 2, "rybi-trh-cukidzi.png", ["s"]],
    ["SETI", 1, 4, "seti.png", ["s"]],
    ["Společenství dobrodruhů", 2, 6, "spolecenstvi-dobrodruhu.png", ["s"]],
    ["Svit luny", 2, 2, "svit-luny.png", ["s"]],
    ["Trails of Tucana", 1, 8, "trails-of-tucana.png", ["s"]],
    ["Triominos", 2, 4, "triominos.png", ["s"]],
    ["Ukijo", 1, 4, "ukijo.png", ["s"]],
    ["Vú dú", 2, 8, "vu-du.png", ["s"]],
    ["Zářihvozd", 1, 4, "zarihvozd.png", ["s"]],
    ["Karak I", 2, 5, "karak-i.png", ["m"]],
    ["Karak II", 2, 5, "karak-ii.png", ["z"]],
    ["Hradní devatero", 2, 5, "hradni-devatero.png", ["s"]],
  ],

  // [datum, hry (název + poznámka), účastníci (slugy), hosté]
  events: [
    { date: "2026-02-27", games: [["Jungo", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-03-13", games: [["Karak I", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-03-20", games: [["Karak I", "Rozšíření"]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-03-27", games: [["Karak II", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-04-10", games: [["Vydry", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-04-17", games: [["Genius Square", null], ["Quartino", null], ["Trio", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-04-30", games: [["Flip 7", null], ["Bájné kostky", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-05-07", games: [["Karak I", "Rozšíření"]], participants: ["s", "m", "z"], guests: ["JB"] },
    { date: "2026-05-15", games: [["SETI", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-05-22", games: [["Karak II", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-05-29", games: [["SETI", null]], participants: ["s", "m", "z"], guests: [] },
    { date: "2026-06-19", games: [["Dej sem totem", null]], participants: ["s", "m"], guests: [] },
    { date: "2026-07-03", games: [["Hradní devatero", null]], participants: ["s", "m"], guests: [] },
  ],

  wishlist: [], // [slug člena, název hry]
};
